csvFilePath = src\\test\\java\\com\\ll\\iod\\testdata1
testFilePath = testfiles
#qa,replica
environment=replica
Browser=edge
reportFolder =test-output\\testReports
sleepTimeOneThousandMs = 1000
jqueryLoadTime = 30
loadingTime = 30
howmanytime=3
TestRunID=5207
TestRailTestPlanID=R5206
TestRunName=hi
TESTRAIL_BASE_URL=https\://sqaloanlogics.testrail.net/
TESTRAIL_USERNAME=anandhan.s@loanlogics.com
TESTRAIL_PASSWORD=Op.iK2QOPU8W9nE/8bo1-U8vtEoMz1Hg5IxmAq0O0
TEST_CASE_RETEST_STATUS=4
TEST_CASE_PASSED_STATUS=1
TEST_CASE_FAILED_STATUS=5
