std=https://stdqaautomation.qa.loanhdsandbox.com/
admin=https://adminqaautomation.qa.loanhdsandbox.com/
parent=https://parentqaautomation.qa.loanhdsandbox.com/
child=https://childqaautomation.qa.loanhdsandbox.com/
TntRegt=https://registration.qa.loanhdsandbox.com/client-registration/home