std=https://replicastdautomation.clarificloud.com/
admin=https://repladmin.clarificloud.com/
parent=https://reptm.clarificloud.com/
child=https://apiautomationchild.clarificloud.com/
TntRegt=https://registration.clarificloud.com/client-registration/home